### ISSUE TITLE
User Testing Second Prototype

### ISSUE THREAD

**Issue by Anniechanster** [deltatrio/web-app#22]
Take the new updated prototype and test again: 

- [x] Test interactive prototype with 5 people

**Comment by refkoer** [comment]
test 1
 
task: find recent list
Navigated to the list fast by using the bottom nav bar.
question about the the classification if it brings you to a page with all the same 
flavour profile.

test 2

task: find beer near you 

Navigated to the map with ease.
asked if there was more information about the map if it was a dead end.

test 3

task: Find product on the map and return to home page

Found the product but struggled going back to home page. Missing buttons? 

Summary of the user testing:
The navigation was smooth I think that we are missing a little bit of content and buttons for a smoother navigating experience.
