### ISSUE TITLE
UX Success Criteria Definitions

### ISSUE THREAD

**Issue by kaylaobritsch** [deltatrio/web-app#7]
This rubric will define our UX success throughout the sprints. This criteria can be edited following the agile approach.

| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Research** | Research not competed | Only some research completed but missing parts | Research is missing a competitive analyses | Quality research completed; with lots of details |
| **Good sprint planning & execution** | Sprints never completed | Some not planned or completed | Sprints planned but not always completed  | Sprints always planned and completed |
| **Quality personas** | No personas completed | Personas not finished | Personas are finished but not designed | Personas are specific to the target audience and well designed |
| **Sitemap** | Only coded pages are included |  |  |  All possible pages are included—showing how they connect |
| **Visual design** | Not thought out | Designed but not suited to personas | Missing some components |  All design included: cards, buttons, links, type and colours |
| **Testable prototype** | No prototype completed | Only basic sketches completed | Only some pages are testable |  High fidelity with all possible pages and sizes user tested |

**Comment by Anniechanster** [comment]
**Research — 3*

We created a google docs and put all of our research in there. We did competitive analysis, features, problem statement, personas, purpose, and an InVision board.


**Good sprint planning & execution — 3*

We planned and completed all the sprints.


**Quality personas — 3*

We made high-fidelity personas with bios, goals, and interests.


**Sitemap — 3*

Sitemap is completed with all pages connected.


**Visual design — 3*

All design is included and custom icons/logos were made. All design is in colour and pictures are also included. 


**Testable prototype — 3*

We did prototypes on variable screen sizes and it is also interactive for people to test it.
