### ISSUE TITLE
Code Success Criteria Definitions

### ISSUE THREAD

**Issue by kaylaobritsch** [deltatrio/web-app#8]
This rubric will define our code success throughout the sprints. This criteria can be edited following the agile approach.

| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Accessibility** | No considerations | Added some alt attributes, nothing else | Just the basics: alt attributes, roles | Accessibility is well considered and tested |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |
| **Reduced code** | Code is just copy and pasted | Jekyll isn't used but some deduplication has occurred | Only basic Jekyll is used |  Jekyll is used as much as possible to deduplicate code and maintain |
| **Responsiveness** | Doesn't work on all screen sizes | Works on half of the screen sizes | Responsive but doesn't look great |  Fully responsive and looks great |
| **Performance** | Super slow | Really slow | Slow |  Fast |
| **Tested** | Not tested | Few things tested | Missing some tests | Tested and fixed multiple times |
| **Design** | Boring | Only some design | Not a catchy design |  Engages the user with exciting experiences |

**Comment by Anniechanster** [comment]
*Accessibility — 2

We considered the accessibility and it is well tested as well. However, we did not add as much as we could. For example, the area roles were not included.

*Code quality — 3

We made sure the code has good semantics and and full indented throughout the code.

*Reduced code — 3

The basic Jekyll was included to have the app running well. We could've added more includes into our code. 

*Responsiveness — 3

We believe the app looks great on all screen sizes and works great.

*Performance — 3

The app is fast and optimized.

*Tested — 3

We tested on different platforms and made other people to test it as well.

*Design — 3

We believe the app is engaging and the design is visually appealing.
